say @e[type=0] Hello and thank you for downloading this mcfunction please do not edit this file. NickerBocker is the creator of this mcfunction so please don't claim it, but you may create your own version

scoreboard objectives add Sheep_White dummy

scoreboard players set @e[type=Sheep] Sheep_White 1 {Color:0}

execute @e[type=Sheep,score_Sheep_White_max=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:Wool",Time:0,NoGravity:1,Data:0}


scoreboard players set @e[type=Item] Spawn_Villager 1 {Item:{id:"minecraft:spawn_egg",Count:1b,tag:{EntityTag:{id:"Villager"}}}}


scoreboard objectives add Parrot_LightBlue dummy
scoreboard objectives add Parrot_LightGray dummy
scoreboard objectives add Parrot_DarkBlue dummy
scoreboard objectives add Parrot_Lime dummy
scoreboard objectives add Parrot_Red dummy
scoreboard players set @e[type=Parrot] Parrot_Red 1 {Variant:0}
scoreboard players set @e[type=Parrot] Parrot_DarkBlue 1 {Variant:1}
scoreboard players set @e[type=Parrot] Parrot_Lime 1 {Variant:2}
scoreboard players set @e[type=Parrot] Parrot_LightBlue 1 {Variant:3}

scoreboard players set @e[type=Parrot] Parrot_LightGray 1 {Variant:4}

gamerule commandBlockOutput false
effect @e[type=!Player] minecraft:invisibility 9999 99 true

effect @e[type=Shulker] minecraft:invisibility 0 0
effect @e[type=Sheep] minecraft:invisibility 0 0

execute @e[type=Parrot,score_Parrot_DarkBlue_min=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:concrete",Time:0,NoGravity:1,Data:11}
execute @e[type=Parrot,score_Parrot_Lime_min=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:concrete",Time:0,NoGravity:1,Data:5}
execute @e[type=Parrot,score_Parrot_LightBlue_min=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:concrete",Time:0,NoGravity:1,Data:3}
execute @e[type=Parrot,score_Parrot_LightGray_min=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:concrete",Time:0,NoGravity:1,Data:8}
execute @e[type=Parrot,score_Parrot_Red_min=1] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:concrete",Time:0,NoGravity:1,Data:14}

execute @e[type=Rabbit] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:carrots",Data:7,Time:0,NoGravity:1}
execute @e[type=Pig] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:stained_hardened_clay",Data:0,Time:0,NoGravity:1,Marker:1}
execute @e[type=Cow] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:stained_hardened_clay",Data:7,Time:0,NoGravity:1}
execute @e[type=Mooshroom] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:red_mushroom",Time:0,NoGravity:1}
execute @e[type=Polar_bear] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:snow",Time:0,NoGravity:1}
execute @e[type=Villager] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:emerald_block",Time:0,NoGravity:1}

execute @e[type=Slime] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:slime",Time:0,NoGravity:1}
execute @e[type=Creeper] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:tnt",Time:0,NoGravity:1}
execute @e[type=Skeleton] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:bone_block",Time:0,NoGravity:1}
execute @e[type=Enderman] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:obsidian",Time:0,NoGravity:1}
execute @e[type=Guardian] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:prismarine",Time:0,NoGravity:1}
execute @e[type=Spider] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:web",Time:0,NoGravity:1}
execute @e[type=Wither_Skeleton] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:coal_block",Time:0,NoGravity:1}
execute @e[type=Shulker_Bullet] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:wool",Time:0,NoGravity:1}
execute @e[type=Zombie] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:stained_hardened_clay",Data:13,Time:0,NoGravity:1}
execute @e[type=Ender_Dragon] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:dragon_egg",Time:0,NoGravity:1}
execute @e[type=Blaze] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:glowstone",Time:0,NoGravity:1}
execute @e[type=Ghast] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:soul_sand",Time:0,NoGravity:1}
execute @e[type=Silverfish] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:stone",Time:0,NoGravity:1}
execute @e[type=Wither] ~ ~ ~ /summon falling_block ~ ~ ~ {Block:"minecraft:skull",Time:0,NoGravity:1,Data:1}

